python:
   version: 3.6
   install:
      - requirements: docs/requirements_doc.txt
      - requirements: requirements.txt
      - method: pip
        path: .
        extra_requirements:
            - docs
   system_packages: true
